### ISSUE TITLE
バージョニングのタイプはISSUEから連動させる

### ISSUE THREAD

**Issue by honma-ambient** [ambient-lab/ambient-tmpl-root#100]
• ISSUEテンプレート
• ISSUEラベル(可能であればテンプレート選択したら該当ラベルがついてほしい)
• コミットメッセージの制約とテンプレート
タイプもISSUEも含んで再検討。

**Comment by k-onodera-ambient** [comment]
ISSUEテンプレートの作成権限がなさそうなので ほんまちゃん( @honma-ambient )に確認中

**Comment by k-onodera-ambient** [comment]
メモ
- issueの段階でバージョニングを考慮した fix, feat, pref などのコミットメッセージの規則を組み込みたい
  - issueを書くのエンジニアならどれに該当するのか判断できるのでそれでよい
  - issueを書くのがアイディアを持った非エンジニアであった場合はどのテンプレートを使って良いかわからない

↓

- エンジニア/非エンジニア用でそれぞれテンプレート一式を用意するか
- 非エンジニア用のissueテンプレート1つと、エンジニア用のテンプレート一式を用意しておくのがよいか

**Comment by k-onodera-ambient** [comment]
GitHub公式では以下のような使い分けを推奨していた
- Discussions： 仕様や処理方式などの議論、方針決め
- Issues: 方針決定後の作業の管理・分類

上記の方法に従うのであれば、「アイディアを持った非エンジニア」の意見はまずdiscussionsに入り、issueはエンジニアが入れることになるので問題なさそう

**Comment by suz-lab-hiroyasu** [comment]
@k-onodera-ambient まずはエンジニアのみ対象でOK

**Comment by k-onodera-ambient** [comment]
[進捗]
- メンバーに意見をいただき、各Issueのタイトルはコミットメッセージに寄せる方針で作成中
   - テンプレートはファイル管理されるので一旦経過をコミットしてdevelopへマージ
- コミットメッセージはIssue No.を含めるが、Issue作成時点では決定する前なのでどうするか検討中

**Comment by k-onodera-ambient** [comment]
fix (バグ、非機能)、feat、prefのISSUEテンプレートを作成しました。
![Image](https://github.com/ambient-lab/ambient-tmpl-root/assets/141118878/94409440-0193-429d-9d68-00fac8abf588)
