### ISSUE TITLE
テンプレートリポジトリのアップデートをプロジェクトリポジトリに反映するコマンド作成(root)

### ISSUE THREAD

**Issue by suz-lab-hiroyasu** [ambient-lab/ambient-tmpl-root#106]
▼コマンドは下記に配置
.devcontainer/features/root/
※テンプレートリポジトリが何か教えてあげないといけないと思う。

**Comment by y-suzuki-152** [comment]
シェルスクリプトでgitコマンド等を実行する予定

> ※テンプレートリポジトリが何か教えてあげないといけないと思う。
こちらはコンテナの環境変数を使う予定
各テンプレートリポジトリ用のdevcontainer-feature.jsonに自身のリポジトリ名を環境変数として追加
プロジェクトリポジトリ視点では親となっているテンプレートリポジトリの値を取得できる

**Comment by y-suzuki-152** [comment]
rootに反映した内容の取り込みと、環境変数の定義を各テンプレートリポジトリで実施中
完了
- root 
  - app
  - infra
残り
- web
- web-tw
- web-mui

**Comment by y-suzuki-152** [comment]
修正内容を全環境に反映完了したためDoneにしました。
