### ISSUE TITLE
CodespacesのOrganizationSecretsの挙動の確認と設定

### ISSUE THREAD

**Issue by suz-lab-hiroyasu** [ambient-lab/ambient-tmpl-root#108]
- "AWS SSO"関係の設定はOrganizationSecretsにして各リポジトリで設定する必要がないようにする。
- 各リポジトリで同一の変数名を設定した場合、各リポジトリの変数が優先されるか？

**Comment by suz-lab-hiroyasu** [comment]
▼Organization
AWS_REGION
AWS_SSO_REGION
AWS_SSO_ROLE_NAME
AWS_SSO_START_URL

▼Repojitory
AWS_SSO_ACCOUNT_ID

**Comment by honma-ambient** [comment]
> 各リポジトリで同一の変数名を設定した場合、各リポジトリの変数が優先されるか？

リポジトリの変数が優先されることを確認。



![Image](https://github.com/ambient-lab/ambient-tmpl-root/assets/136694820/f6307dc1-5f29-4747-8d93-b72fbec25983)
