### ISSUE TITLE
テンプレートリポジトリからリポジトリを作成した時にテンプレートから引き継がれるものの確認

### ISSUE THREAD

**Issue by suz-lab-hiroyasu** [ambient-lab/ambient-tmpl-root#116]
引き継がれないものはマニュアルで設定する必要がある。
→最終的には自動化。

**Comment by honma-ambient** [comment]
結論、デフォルトブランチ以外はリポジトリ作成時と同様で、全てデフォルト設定になっていることが判明。
組織側のリポジトリ設定も確認したが、特段引き継ぎできるような設定は見当たらずでした。


## テンプレートから引き継がれないもの↓

### General
- Discussions
  - 許可が外れる
- Pull Requests
  - 「コミットマージ」、「スカッシュマージ」、「リベースとマージ」が全て許可されるようになる
- Always suggest updating pull request branches(プル リクエスト ブランチを更新することを常に提案します)
  - 許可が外れる
- Allow auto-merge
  - 許可が外れる
- Automatically delete head branches(headブランチを自動的に削除)
  - 許可が外れる

### Branches
- Branch protection rules
  - 設定が全て外れる
- Rulesets
 - 作成してたルールセットが外れる


### Environments
- 設定が全て外れる

### Codespaces
- Prebuild configuration
  - 設定が全て外れる

### Code security and analysis
- 設定が外れる（全てデフォルトに）
- Dependabot version updates
  - ` .github/dependabot.yml`が継承されてるのに、再度設定し直し

**Comment by honma-ambient** [comment]
Github CLI使って自動化できるかは調べる必要あり

**Comment by suz-lab-hiroyasu** [comment]
@honma-ambient プロジェクトリポジトリの作成方法(テンプレートから)と、その後にやるべきアクションをドキュメンテーション

**Comment by suz-lab-hiroyasu** [comment]
@honma-ambient
とりあえずリポジトリにいれて完了(ブランチ＆Push&PR&マージ)
