### ISSUE TITLE
fix: ドキュメントをREADMEにするかWikiにするか検討

### ISSUE THREAD

**Issue by suz-lab-hiroyasu** [ambient-lab/ambient-tmpl-root#122]
Wikiはテンプレートから引き継げるのか？
引き継げなければREADME

**Comment by honma-ambient** [comment]
結論: Wikiも引き継ぎ不可。→なのでREADMEに落とし込む

**Comment by honma-ambient** [comment]
# Organization のプロフィール ページへドキュメンテーションファイルを移行させたい。


## 詳細

GitHubにはOrganization専用のプロフィールリポジトリを作成することができる。
Organization についての情報を共有することができる。
対象は`.github` リポジトリを用意した運用となる。

▼参考例
- https://github.com/microsoft
- https://github.com/facebook/.github


▼機能の説明
[Organizationのプロフィールのカスタマイズ](https://docs.github.com/ja/organizations/collaborating-with-groups-in-organizations/customizing-your-organizations-profile)


▼何が課題か？
- 親テンプレートから派生したフォークリポジトリにもドキュメントを更新していかないといけない状況。
- テンプレートのリポジトリで管理するドキュメントテーションが増えるとリポジトリで管理する容量も増える。

組織のプロフィール専用リポジトリがあるため、
全リポジトリやwebなど特化したリポジトリに、共通するドキュメンテーションをそっちに移行できないか？


## 期待する動作

- 共通できるドキュメント内容の場合、テンプレートリポジトリのREADMEから、組織プロフィールリポジトリのREADMEへリンクして誘導。
- テンプレートリポジトリ運用者は、`.github`リポジトリにREADME側で今後管理するだけになる。
- テンプレートリポジトリのREADMEに、`.github`リポジトリのREADMEへ遷移させるよう内容を記載する。


## 影響

_テンプレートリポジトリに記載してるREADME内容とその他ドキュメント資料、_

**Comment by suz-lab-hiroyasu** [comment]
@honma-ambient 
下記を適材適所に使い、今のドキュメントをどう移動すればいいか検討。
- Organization のプロフィール 
- Page
- Wiki

**Comment by honma-ambient** [comment]
結論、ドキュメントとしては、wikiのほうが管理しやすい。
テキスト、画像、コードで自由記述が柔軟にできる。また、変更履歴も誰が操作したのかわかるため。


それぞれの利用用途↓

- Organization のプロフィール
  - 組織の概要を示す
  - 組織のウェブサイトやブログへのリンクを提供する
  - 組織の主要なリポジトリを示す

- Page
  - 組織のニュースやイベントを発表する
  - 組織の製品やサービスの説明を提供する
  - 組織の採用情報を提供する

- Wiki
- 組織のプロジェクトの使い方や設計方法を説明する
- 組織の技術的なドキュメントを提供する
- 組織の歴史や文化を示す


Wikiは、Markdown を使用してテキスト、画像、コードを自由に記述できる
Organization のプロフィールは、組織の基本的な情報を表示するためのもの
Pageは、ページ単位で管理するためのもの
