### ISSUE TITLE
feat: バージョニングのタイプはISSUEから連動させるのドキュメント化

### ISSUE THREAD

**Issue by suz-lab-hiroyasu** [ambient-lab/ambient-tmpl-root#137]
## 詳細

バージョニングのタイプはISSUEから連動させるのドキュメント化

## 期待する動作

Readmeから辿れるかたちで上記のドキュメントを確認できる

## 実装アイデア

なし

## 関連する情報

#100

**Comment by k-onodera-ambient** [comment]
対応完了

バージョニングとコミットメッセージの関係性は別項目で記述済みのため、今回作成したドキュメントには記載せず、Issueテンプレートについてと各テンプレートの規定値のことをドキュメント化しています。

- doc/readme/issue/ に ドキュメントを追加
- 直下Readmeには上記ドキュメントへのリンクを作成
   - https://github.com/ambient-lab/ambient-tmpl-root#issue-%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6

**Comment by honma-ambient** [comment]
確認したのでクローズ

**Comment by k-onodera-ambient** [comment]
ありがとうございます！
