### ISSUE TITLE
TeamのReviewerの設定のまとめとPR作成時に自動でTeamが設定されるように

### ISSUE THREAD

**Issue by suz-lab-hiroyasu** [ambient-lab/ambient-tmpl-root#151]
- TeamのReviewerの設定をどうすべきかまとめる。
- PR作成時に自動でTeamが設定されるようにする。

**Comment by k-onodera-ambient** [comment]
● TeamをReviewerに設定する方法

デフォルトではPRのReviewer選択でTeamは選択できない。
以下の設定を行うことで選択できるようになる。

- リポジトリ画面
  - [Settings]
    - [Collaborators and teams]
      - [Manage access] 対象のチームに書き込み権限を付与する
- Team画面
  - [Settings]
    - [General]
      - [Team visibility]「Visible」にする
        - Reviewsにチームが指定できるようになる  
          この場合チーム自体がReviewerになる
    - [Code review]
      - [Enable auto assignment]にチェックを入れる
        - Reviewsにチームを指定しPR作成するとチームがチームメンバーに置き換わるようになる
        - [Team review request] 未チェック時、置き換えではなくチームメンバー + チームになる

● 実際に必要な設定

- Team画面
  - [Settings]
    - [General]
      - [Team visibility]「Visible」にする
    - [Code review]
      - [Enable auto assignment]にチェックを入れる


**ambient-dev-privateは[Team visibility]「Secret」なので「Visible」にしないとReviewer指定できません。**

スライドの"Github Teamと権限"では以下のように記載されていました。
> <project>-privateユーザーがレビューを行う
レビューだけを考えれば、ambient-dev-privateを「Visible」にするのが好ましいと思います。
変更不可の場合、PRテンプレートで個人(複数人可)を固定で指定しておくか、現在のようにPR作成者が毎回選択する方法になると思います。

● ご相談
ambient-dev-privateの [Team visibility] を 「Visible」にしても問題ないでしょうか？

**Comment by suz-lab-hiroyasu** [comment]
@k-onodera-ambient 
ambient-dev-privateの [Team visibility] を 「Visible」にしても問題ないでしょうか？
→ 問題ありません。

@honma-ambient 実験用のプライベートリポジトリを用意

**Comment by honma-ambient** [comment]
@k-onodera-ambient 
実験用のリポジトリ作りました

リポジトリの設定は初期設定のためブランチ保護などは無効になってます
https://github.com/ambient-lab/ambient-sandbox

**Comment by k-onodera-ambient** [comment]
### 検証結果

#### PRテンプレート - 設定不可

設定項目なし

#### workflow - 不採用

ググるとできそうな感じはありますが、実際にやってみるとできませんでした。
(レビュアーにチームを指定するとGithubAPIはレスポンス200を返しているのにReviewersが空のまま)

間接的なやり方にはなりますが、定義しておいたユーザの配列から1名をランダム選出してReviewer設定するようなやり方であれば可能ですが、workflowの実行を待つのでレビュアーが入るまで少しラグがあるのと、チームのメンバーを入れ替えた時に連動して変わっていくわけではないので微妙なやり方だと思います。

#### CODEOWNERS - 採用

.github/CODEOWNERSを記述してコードオーナーを設定します
https://docs.github.com/ja/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners

コードオーナーを設定すると**プルリクエスト作成時のデフォルトのReviewsに設定されるようになります**
これによってReviewsにチームが設定された時にAuto Assignが正しく機能することも確認済みです。

この検証時点ではCODEOWNERSに ` * @ambient-lab/ambient-dev-private ` と設定したのでambient-dev-privateチームが全てのファイルのオーナーになっていますが、ユーザ・チームが特定ディレクトリ・拡張子等に対して指定可能なので柔軟な設定も可能です

**Comment by k-onodera-ambient** [comment]
[追記] 実験用のリポジトリは検証に大いに役立ちました。ありがとうございます。

**Comment by suz-lab-hiroyasu** [comment]
@k-onodera-ambient まずは、すべてのテンプレートリポジトリに上記の設定を行う。
可能であれば、チーム名はハードコードじゃない方がいいけど。。。

**Comment by k-onodera-ambient** [comment]
CODEOWNERを動的な値にすることはできませんでした。
テンプレートリポジトリは利用者(トヨタ等)がいることを前提に考える必要があると思いますが、git管理されているCODEOWNERにambient orgの内部的なチーム名を直接書いておくのは好ましくありません。
これらを踏まえ、チーム宛の自動アサイン設定は残しつつもCODEOWNERによるReviewer自動設定はやめておくのが良いと考えます。

**Comment by suz-lab-hiroyasu** [comment]
ambientチームが入るのは大丈夫
テンプレートを使ったプロジェクトの方で、しかるべきチームに変更
その運用ドキュメントを記載。

**Comment by k-onodera-ambient** [comment]
wikiの[プルリクエストについて]の子項目としてReviewerとCodeOwnerについて追記しました。
https://github.com/ambient-lab/ambient-tmpl-root/wiki#reviewers%E3%81%AE%E8%87%AA%E5%8B%95%E8%A8%AD%E5%AE%9A%E6%96%B9%E6%B3%95
