### ISSUE TITLE
Wikiの運用方法のドキュメント化とREADMEのWiki移行

### ISSUE THREAD

**Issue by suz-lab-hiroyasu** [ambient-lab/ambient-tmpl-root#152]
- WikiとかPageとかプロフィールとかの利用指針
- Wikiの運用方法を記載
- READMEの情報をWikiに移行

**Comment by honma-ambient** [comment]
一旦、既存のREADMEの内容をもとにwikiに移設。
https://github.com/ambient-lab/ambient-tmpl-root/wiki


リポジトリにあるREADME関連の修正を行う

**Comment by honma-ambient** [comment]
### READMEをWikiへ移動
https://github.com/ambient-lab/ambient-tmpl-root/wiki



### Wiki運用手順
https://github.com/ambient-lab/ambient-tmpl-root/wiki/Wiki%E3%81%AE%E9%81%8B%E7%94%A8%E6%96%B9%E6%B3%95
