### ISSUE TITLE
MainにPRマージするときに該当するDevelopにマージされたPRをわかるように

### ISSUE THREAD

**Issue by suz-lab-hiroyasu** [ambient-lab/ambient-tmpl-root#153]
Develop → Main
↓
Develop → Main

前回のマージ以降で、DevelopにマージされたPR(これらの内容が今回MainへのPRでマージされる)がわかるように
できればリリースノートに反映したい。

**Comment by k-onodera-ambient** [comment]
developブランチにマージしたPRにマイルストーンを設定するGithubActionsを作成しました。

PRの紐付け先は「Mainリリース W{週番号}」という名称のマイルストーンになります。
存在しない場合は作成、あれば紐付けだけを行います。

PRのマージをトリガーにマイルストーンの作成を行うため、developへのマージが1週間なかった場合、その週のマイルストーンは作成されません。
(マイルストーン作成はスケジュールされた別Actionで実施することも考えましたがやっていません)

**Comment by k-onodera-ambient** [comment]
wiki追記中

**Comment by k-onodera-ambient** [comment]
前回のMainマージ(リリース)時点からdevelopにマージされたPRをマイルストーンで管理するworkflowを作成しました。

フローは以下の通りです
- main/developへのマージ時にマイルストーンが存在しない場合
  - マイルストーン「Merged Pull Requests YYYY-MM-01 ~」を作成
- developへのマージ時
  - マージしたPRをマイルストーン「Merged Pull Requests YYYY-MM-01 ~」に紐づける
- mainへのマージ時
  - マイルストーン「Merged Pull Requests YYYY-MM-01 ~」を「Merged Pull Requests YYYY-MM-01 ~ YYYY-MM-02」にリネームしてクローズする
  - マイルストーン「Merged Pull Requests YYYY-MM-02 ~」を作成

**Comment by k-onodera-ambient** [comment]
wikiページ「リリース」にマイルストーンについて記載しました
https://github.com/ambient-lab/ambient-tmpl-root/wiki/%E3%83%AA%E3%83%AA%E3%83%BC%E3%82%B9#%E3%83%9E%E3%82%A4%E3%83%AB%E3%82%B9%E3%83%88%E3%83%BC%E3%83%B3%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6
