### ISSUE TITLE
fix:  Wikiのテンプレートアップデートの反映系を別ページにする

### ISSUE THREAD

**Issue by suz-lab-hiroyasu** [ambient-lab/ambient-tmpl-root#168]
## 詳細

_修正する非機能について説明してください。_

## 関連する情報

_関連する Issue やドキュメントがある場合、こちらにリンクを貼ってください。_

**Comment by honma-ambient** [comment]
memo

Homeのページに集約されてる状況のため別ページに用意して管理する

**Comment by honma-ambient** [comment]
新規Wikiページに移設

[テンプレートリポジトリについて](https://github.com/ambient-lab/ambient-tmpl-root/wiki/%E3%83%86%E3%83%B3%E3%83%97%E3%83%AC%E3%83%BC%E3%83%88%E3%83%AA%E3%83%9D%E3%82%B8%E3%83%88%E3%83%AA%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6#%E3%83%86%E3%83%B3%E3%83%97%E3%83%AC%E3%83%BC%E3%83%88%E3%83%AA%E3%83%9D%E3%82%B8%E3%83%88%E3%83%AA%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6)
