### ISSUE TITLE
fix:  WikiのGit操作系を別ページにする

### ISSUE THREAD

**Issue by suz-lab-hiroyasu** [ambient-lab/ambient-tmpl-root#169]
## 詳細

_修正する非機能について説明してください。_

## 関連する情報

_関連する Issue やドキュメントがある場合、こちらにリンクを貼ってください。_

**Comment by honma-ambient** [comment]
memo

Homeのページに集約されてる状況のため別ページに用意して管理する

**Comment by honma-ambient** [comment]
Wikiに新しいページ [Gitのお作法](https://github.com/ambient-lab/ambient-tmpl-root/wiki/Git%E3%81%AE%E3%81%8A%E4%BD%9C%E6%B3%95)を用意して
バージョニングやプルリクエスト関連の内容を全てこちらに集約。
