### ISSUE TITLE
feat: ISSUEテンプレートのアップデート

### ISSUE THREAD

**Issue by suz-lab-hiroyasu** [ambient-lab/ambient-tmpl-root#171]
# AS-IS

Feat - 仕様・機能追加
マイナーリリース - 後方互換性のある機能追加をします。Readme修正もこちらを使用します。

Fix - バグ修正
パッチリリース - 後方互換性のあるバグ修正をします

Fix - 非機能
パッチリリース - 非機能の修正をします

Pref - 仕様・機能変更
メジャーリリース - 後方互換性のない機能変更やバグ修正をします

# TO-BE

(MECE)
1_Fix
・バグ修正
・コンテンツ修正
・ドキュメント修正
・リファクタリング
2_Feat
・機能の追加・変更・削除(後方互換性あり)
・コンテンツの追加・変更・削除(後方互換性あり)
・ドキュメントの追加・変更・削除(後方互換性あり)
3_Pref
・機能の追加・変更・削除(後方互換性なし)
・コンテンツの追加・変更・削除(後方互換性なし)
・ドキュメントの追加・変更・削除(後方互換性なし)
0_Blank

※テンプレートは11個

**Comment by k-onodera-ambient** [comment]
### 対応完了

11個のテンプレートを作成しました。

Blankの利用優先順位はテンプレートの中では低い方だと思いまして、表示順は1番下になるように設定しています。

旧テンプレートだとFixなら「fix, patch release」といった具合にラベル設定をしていましたが、今回のアップデートでは旧テンプレートでのラベリング仕様は踏襲しつつ次のラベルも追加しています。
- 機能 - https://github.com/ambient-lab/ambient-tmpl-root/labels/functional
- コンテンツ - https://github.com/ambient-lab/ambient-tmpl-root/labels/contents
- ドキュメント - https://github.com/ambient-lab/ambient-tmpl-root/labels/documentation
- リファクタリング - https://github.com/ambient-lab/ambient-tmpl-root/labels/refactoring
- blank - https://github.com/ambient-lab/ambient-tmpl-root/labels/blank%20issue


### Issue作成画面での表示


![Image](https://github.com/ambient-lab/ambient-tmpl-root/assets/141118878/f7174f69-2d1b-4016-bb67-af6b3a05a899)

(Report a security vulnerabilityは特に作成したものではなくGithub側の機能として表示されているもののようです)

**Comment by k-onodera-ambient** [comment]
#181 
Blank Issueが2重で表示されていた問題は修正済みです。
