### ISSUE TITLE
Organizationにデフォルト用ラベルを用意する

### ISSUE THREAD

**Issue by honma-ambient** [ambient-lab/ambient-tmpl-root#178]
## 詳細

Organization側のリポジトリ設定にデフォルトラベルの設定ができるので、
issueテンプレートとかで利用してるラベル群を全部用意したい。

リポジトリ作ってからラベルを再度作る手間が無くなる。
全リポジトリに対してラベル継承されるので、非常に楽になる。

## 関連する情報

_関連する Isssue やドキュメント、スクリーンショット、または参考情報がある場合、こちらにアップロードまたはリンクを貼ってください。_

**Comment by k-onodera-ambient** [comment]
contents、documentation、functional、refactoring、blank issue
fix, feat, pref, patch release, minor release, major release

Issueテンプレートで指定しているのは上記のlabelです。documentation以外は追加したものになります

**Comment by honma-ambient** [comment]
work in progressも入れる

**Comment by honma-ambient** [comment]
メモ

Organizationのラベルを設定後、既存リポジトリには反映されない →  状況に応じて都度手動作成かスクリプト化で作成
今後の新規リポジトリ作成にはデフォルトラベルが付与される

**Comment by honma-ambient** [comment]
設定は完了したのでクローズする
