### ISSUE TITLE
feat: GitHubでスクラムのバックログの管理方法の検討

### ISSUE THREAD

**Issue by suz-lab-hiroyasu** [ambient-lab/ambient-tmpl-root#183]
## 詳細

▼スクラム
https://shiftasia.com/ja/column/%E3%82%B9%E3%82%AF%E3%83%A9%E3%83%A0%E3%81%AE%EF%BC%93%E3%81%A4%E3%81%AE%E4%BD%9C%E6%88%90%E7%89%A9/

プロダクトバックログ(タスク)
スプリントバックログ(プロダクトバックログの子タスク)

GitHubのタスク(ISSUE)は親子構造が作れない

▼スクラムとGitHubのからみ
https://zenn.dev/ncdc/articles/55cc05c1a65292

### タスクリスト
- [ ] TODOで何かあればテキストで書くこともできる
- [ ] #123

タスクリストは子タスクとして使えるかも
ISSUEとしてはフラットなので、PBIとSBIを区別できるよにしたい
→ラベルを使う？カスタムフィールド？リポジトリ？

ISSUEはリポジトリに紐づく
- PBI:予約する: プロジェクトリポジトリ作る？
  - SBI: UI作成: フロントエンドリポジトリ
  - SBI: API作成: バックエンドリポジトリ
→ 別リポジトリのISSUEをタスクリストで参照できるか？

**Comment by suz-lab-hiroyasu** [comment]
@fujiyamahiroki  なんかあったら @suz-lab-hiroyasu に質問。

**Comment by fujiyamahiroki** [comment]
```[tasklist]
### タスクリスト
- [ ] TODOで何かあればテキストで書くこともできる
- [ ] #182 test
```

**Comment by suz-lab-hiroyasu** [comment]
@fujiyamahiroki 
▼リポジトリの種類(複数リポジトリの場合の例)
-プロジェクトリポジトリ ← PBIのみ
-フロントエンドリポジトリ ← SBIのみ
-バックエンドリポジトリ ← SBIのみ
※リポジトリが一つでいいプロジェクトはPBIとSBIが両方入る。
上記の区別をラベルでやるか？カスタムフィールドでやるか？

**Comment by suz-lab-hiroyasu** [comment]
@fujiyamahiroki 
別リポジトリのISSUEをタスクリストで参照できるか？

**Comment by suz-lab-hiroyasu** [comment]
@fujiyamahiroki 上記の管理方法の文書かまで10/12(木)までにやってほしい。

**Comment by fujiyamahiroki** [comment]
```[tasklist]
- [ ] TODOで何かあればテキストで書くこともできる
- [ ] #123
```

**Comment by fujiyamahiroki** [comment]
@suz-lab-hiroyasu 
githubでのスクラムのバックログの管理方法ですがPBIとSBIでそれぞれリポジトリを分け、これら２つを管理するプロジェクトリポジトリを作成するはいかがでしょうか。
提案する理由としてはリポジトリごとにPBlとSBlを分けるので管理のしやすさが採用する理由になります。

リポジトリが1つでいいプロジェクトに関してはラベルで PBIとSBIを区別するのが最適だと思われます。選定の際にラベルとカスタムフィールドどちらにするのかの話がありましたが、メリット・デメリットを比較しラベルのほうが適していると判断しました。以下、ラベルとカスタムフィールドのメリット・デメリットです。

ラベル
メリット
・シンプルさ
・柔軟性
・可視性
・検索とフィルタリング

デメリット
・情報の制約
・限られたカスタマイズ

カスタムフィールド
メリット
・カスタマイズ性
・データの構造化
・レポートの作成

デメリット
・複雑性
・学習コスト
・導入の遅延

以上のことからラベルは単純なカテゴリ分類に適していて、カスタムフィールドはより詳細なカスタマイズをしたい場合に
適しているので今回は同一リポジトリでのPBlとSBlのカテゴリ分けだと思ったのでラベルを提案いたしました。

また,別リポジトリのISSUEをタスクリストで参照できるか？という点ですが
- [ ] [外部リポジトリのSBI](https://github.com/ambient-lab/ambient-tmpl-web-tw/issues/62)
```
[ ] [外部リポジトリのSBI](https://github.com/ambient-lab/ambient-tmpl-web-tw/issues/62)
```
このようにして別リポジトリのISSUEを参照することが可能です。
ですので、PBIとSBIでそれぞれリポジトリを分け、これら２つを管理するプロジェクトリポジトリを作成する方法を提案いたしました。

**Comment by fujiyamahiroki** [comment]
@suz-lab-hiroyasu 
自分では問題ないと思っていますが、こちらで問題ないでしょうか？
木曜までということだったので早めに連絡をいただけると問題があった場合に対応がしやすいので
ご連絡いただけると幸いです

**Comment by suz-lab-hiroyasu** [comment]
@fujiyamahiroki 基本的に上記で問題ありません。
下記、フィードバックです。

- リポジトリが一つでも複数でもPBIとSBIはラベル付けするようにしてください。
- PBIの中でタスクリストでSBIを記載する場合ですが、リポジトリが一つの時と複数の時に機能の違いがあると思います。
  - 一つの場合: タスクリストの機能でSBIのISSUEのステータスが自動で反映されISSUEの関連付けも行われる
  - 複数の場合: ただの外部リンクなので、一つの場合の連携機能は利用できない。

上記を踏まえ、管理方法を運用ドキュメントとしてまとめてください。
リポジトリが一つの場合と複数の場合で分けて書くといいと思います。

**Comment by fujiyamahiroki** [comment]
# GitHubを用いたスクラムのバックログの管理方法について ※複数リポジトリ
## 変更履歴
10月11日　作成
## 管理方法
### リポジトリについて
PBl(プロダクトバックログ)とSBl(スプリントバックログ)をそれぞれ別のリポジトリで管理を行い
PBlとSBlを管理する3つ目のリポジトリとしてプロジェクトリポジトリを作成して管理を行います。
### PBlについて
PBl専用のリポジトリを作成してそのリポジトリにPBlを登録して管理を行って下さい。その際に
PBl専用のラベルを設定をしてください。SBlとの紐づけにはタスクリストを使用して下さい。

- [ ] [外部リポジトリのSBI](https://github.com/ambient-lab/ambient-tmpl-web-tw/issues/62)
```
- [ ] [外部リポジトリのSBI](https://github.com/ambient-lab/ambient-tmpl-web-tw/issues/62)
```

**Comment by fujiyamahiroki** [comment]
@suz-lab-hiroyasu 
確認お願いします
# GitHubを用いたスクラムのバックログの管理方法について ※単一のリポジトリ
## 変更履歴
10月11日　作成
## 管理方法
### リポジトリについて
PBl(プロダクトバックログ)とSBl(スプリントバックログ)を同じリポジトリで管理を行い
PBlとSBlが同じリポジトリになるのでPBlとSBlでそれぞれラベルを設定して下さい。
### PBlについて
PBl専用のラベルを設定を行って下さい。
SBlとの紐づけにはタスクリストを使用して下さい。

- [ ] TODOで何かあればテキストで書くこともできる
- [ ] #123

```
- [ ] TODOで何かあればテキストで書くこともできる
- [ ] #123
```
上記のように記載することでタスクリストを設定することができます。
ISSUEの番号を設定することでタスクリストの機能であるISSUEのステータスが自動で反映されISSUEの関連付けも行われます。

### SBlについて
SBl専用のラベルを設定を行って下さい。
