### ISSUE TITLE
fix: オーガニゼーション外のユーザーもプロジェクトリストはみれるのか？

### ISSUE THREAD

**Issue by suz-lab-hiroyasu** [ambient-lab/ambient-tmpl-root#184]
## 詳細

プロジェクトが見れたが
オーガニゼーション外のユーザーもプロジェクトリストはみれるのか？

**Comment by fujiyamahiroki** [comment]
@suz-lab-hiroyasu 
現状の状態を確認したところ8つのプロジェクトを見ることができました。それぞれの
プロジェクトの詳細は「You cant see item」と表示されてみることができませんでした。

自分のgithubアカウントのoranizaitions確認したところambinet-labのmemberになっていました。
memberになっているのでプライベートに設定されているプロジェクトを見ることができましたが、
そのプロジェクトの詳細についてはプロジェクトごとにアクセス権限が必要かと思われるので「You cant see item」
と表示されている状態だと思われます。

オーガニゼーション外のユーザーもプロジェクトリストはみれるのか？という問題ですが
プロジェクトがプライベートに設定されているのでオーガニゼーション外のユーザーは見ることができないと思われます

**Comment by suz-lab-hiroyasu** [comment]
@fujiyamahiroki
適当なメールアドレスでオーガニゼーションに参加してないGitHubアカウントを作成して、
上記を確認

**Comment by fujiyamahiroki** [comment]
@suz-lab-hiroyasu 
オーガニゼーションに参加してないGitHubアカウントでambient-labを確認したところプロジェクトリストを見ることはできませんでした。以下の画像は実行結果です。
![Image](https://github.com/ambient-lab/ambient-tmpl-root/assets/146707599/c12b87c6-518b-4911-b71a-a0ff19f34a96)
![Image](https://github.com/ambient-lab/ambient-tmpl-root/assets/146707599/c3ecf83d-ab59-48d8-9b70-a6e10ef89d60)
![Image](https://github.com/ambient-lab/ambient-tmpl-root/assets/146707599/bd8c9628-1c9d-4b55-8bd0-53f425f4e141)
