### ISSUE TITLE
feat: DependaBotグループの運用のドキュメント化

### ISSUE THREAD

**Issue by suz-lab-hiroyasu** [ambient-lab/ambient-tmpl-root#185]
## 詳細

_作業内容について説明してください。_

## 期待する動作

_どのような動作を期待しているかを明示してください。_

## 実装アイデア

_アイデアや提案を共有してください。_

## 関連する情報

_関連する Isssue やドキュメント、スクリーンショット、または参考情報がある場合、こちらにアップロードまたはリンクを貼ってください。_

**Comment by honma-ambient** [comment]
wikiに
[Dependabot について](https://github.com/ambient-lab/ambient-tmpl-root/wiki/Dependabot-%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6)を記載

**Comment by suz-lab-hiroyasu** [comment]
@honma-ambient  ISSUEの体系に合わせる。
