### ISSUE TITLE
fix: Blank Issueは調査等でも利用することを記載

### ISSUE THREAD

**Issue by suz-lab-hiroyasu** [ambient-lab/ambient-tmpl-root#187]
## 詳細

_修正する内容について説明してください。_

## 関連する情報

_関連する Isssue やドキュメント、スクリーンショット、または参考情報がある場合、こちらにアップロードまたはリンクを貼ってください。_

**Comment by k-onodera-ambient** [comment]
説明文を追記しました。
テンプレートの内容は変更していません。


![Image](https://github.com/ambient-lab/ambient-tmpl-root/assets/141118878/6ad7e63e-9aae-45e0-9db2-f48440dbf243)
