### ISSUE TITLE
fix: PJフィードバック対応

### ISSUE THREAD

**Issue by honma-ambient** [ambient-lab/ambient-tmpl-root#197]
一旦箇条書きレベルのため、細分化必要あり。

## FB対応

- issueテンプレート起票のドキュメント内容をもっとわかりやすくしていく
- フォークリポジトリにrootの最新ソースコードを取り込む必要があり
- blank issueはテンプレート一覧表示として、使用頻度高いのでとりあえず上にしたいが、現状無理なので消す。
- バージョニング自動生成の仕組みがわかりずらいのでドキュメントにシーケンス図を追加
- web系のドキュメントを作っていく
  - Amplifyの初期構築手順
  - npmパッケージ関連の更新時などの確認作業手順
- project.envの影響があるためamplify.ymlは廃止する。(Amplify Consoleで利用する環境変数はAmplify Consoleで指定する運用になったため)
  - 影響テンプレートリポジトリ
    - ambient-tmpl-web
    - ambient-tmpl-web-tw
    - ambient-tmpl-web-mui

- ↓の内容をドキュメントとして追加
  - issueにあげるか判断つかない場合は、discussionsを利用する
  - プルリクエストのテンプレートは、あくまでテンプレート用。プロジェクト側で適宜内容を変えてもらう運用で
  - プルリクエストのマージ許可設定

- テンプレートリポジトリ→プロジェクトリポジトリの作業を簡易化
  - テンプレートに更新が入ると都度ソースコードの認識合わせが必要のため

**Comment by suz-lab-hiroyasu** [comment]
@honma-ambient honma-ambient 本イシューは、新しいプロジェクト管理方法のPBIとSBIの状態にして完了

**Comment by honma-ambient** [comment]
@suz-lab-hiroyasu @k-onodera-ambient 
下記の通りPBIとSBI化させたため本件はクローズ

https://github.com/ambient-lab/ambient-tmpl/issues/12
https://github.com/ambient-lab/ambient-tmpl/issues/13
https://github.com/ambient-lab/ambient-tmpl/issues/14
