### ISSUE TITLE
リポジトリ名をambient-tmpl-xxxに変更

### ISSUE THREAD

**Issue by suz-lab-hiroyasu** [ambient-lab/ambient-tmpl-root#80]
ドキュメント名やリンクも変更する必要がある。

**Comment by honma-ambient** [comment]
## 対応状況

下記の通りリポジトリ名は更新済みです

| 変更前 | 変更後 |
| --- |--- |
| dev-root | ambient-tmpl-root |
| dev-web | ambient-tmpl-web |
| dev-web-tw | ambient-tmpl-web-tw |
| dev-web-mui | ambient-tmpl-web-mui |
| dev-app | ambient-tmpl-app |
| dev-infra | ambient-tmpl-infra |


引き続き、README.md関連の更新作業に着手

**Comment by honma-ambient** [comment]
更新作業が残ってるのでissue Openします

**Comment by honma-ambient** [comment]
リポジトリ名を変えてCodespacesを起動するとエラーになって起動しないことが発生。
devcontainer.jsonの参照先が怪しいので調査

**Comment by honma-ambient** [comment]
READMEの内容更新含めて、作業は完了
