### ISSUE TITLE
Codespacesでコード書いてると途中で止まる事象の確認と対策

### ISSUE THREAD

**Issue by suz-lab-hiroyasu** [ambient-lab/ambient-tmpl-root#84]
- 途中で止まるような情報をネットで調べる
- 関係する設定があるか調べる(セッションタイムアウト時間とか)

無いなら無いでOK(完了)

**Comment by k-onodera-ambient** [comment]
"止まる"や"フリーズ"等のキーワードで情報を検索してみましたがヒットしないため、認知された事象ではなさそうです。

自分が実際に起こった似たような事象としては、Chrome拡張の「SessionBox」を用いてタブ毎のログインセッションを独立させた場合に、Codespacesが時間の経過等で接続が切れてから再接続すると画面がリロードを繰り返して接続できないということはありました。


事象の再現もできないため調査はここまでとします。
追加調査が必要な場合は"止まる"とはどのような状態で、ブラウザのコンソールにどのようなエラーが出ているか等の詳細を伺った上で対応させていただきたいです。

**Comment by suz-lab-hiroyasu** [comment]
@k-onodera-ambient  はい、何かあったら、改めてISSUE化します。
